Bulk commit of preptool work.
This commit introduces preptool functionality, through a --preptool
output mode.  With reservation for some points for which issues has
been raised, this follows the spedicfication in RFC7998.

The preptool currently takes vocabulary v3 input, and produces
prepped output.  When work on the text formatter commences, the idea
is that the input xml source will always be run through v2v3
conversion and preptool processing before the output formatting, in
order to increase consistency and reduce complexity of the output
formatter.

There are also some changes which are not related to the preptool
functionality: The tox tests have been changed to add testing under
Python 3.6, and removed test runs for Python 3.3.  Although there is
no intention of breaking compatibility with Python 3.3, it may happen
eventually since there will not be any release testing with that
version of Python.

The v2v3 converter in some cases could insert <seriesInfo> elements
with only a name= attribute, because the required seriesNo= attribute
on <rfc> was missing.  This has been changed.

In order to work around a debilitating issue with relax-ng validation
in libxml2 (time to validate increases exponentially with number of
attributes on the root element:
https://bugzilla.gnome.org/show_bug.cgi?id=133736) some empty
attributes on <rfc> are removed during processing; for instance
obsoletes="" and updates="".  They don't contribute information, but
increase validation time with a factor ~20.

In order to identify the unicode scripts needed to display a document,
a module to efficiently identify the scripts related to unicode
codepoints has been written.  The 'uniscripts' module which was
originally intended to be used for this turned out not to be viable.
The new 'scripts' module can be broken out for separate release as a
library module, if desired.

In order to work with vocabulary v3 input, the parser has been
slightly modified to not do input validation according to rfc2629.dtd
if not appropriate.
 - Legacy-Id: 2409

diff --git a/cli/Makefile b/cli/Makefile
--- a/cli/Makefile
+++ b/cli/Makefile
@@ -4,6 +4,7 @@
 #svnrev	:= $(shell svn info | grep ^Revision | awk '{print $$2}' )
 datetime_regex = [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9][T_ ][0-9][0-9]:[0-9][0-9]:[0-9][0-9]
 version_regex =  [Vv]ersion [2N]\(\.[0-9N]\+\)\+\(\.dev\)\?
+date_regex = [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]
 
 
 rfcxml= \
@@ -17,6 +18,17 @@ rfctest     = $(addsuffix .tests, $(basename $(rfcxml)))
 rfctxtfiles = $(addprefix tests/out/, $(rfctxt))
 rfctests    = $(addprefix tests/out/, $(rfctest))
 
+draftxml = \
+	draft-template.xml		\
+	draft-miek-test.xml		\
+#
+
+draftxmlfiles = $(addprefix tests/input/, $(draftxml))
+drafttxt      = $(addsuffix .txt, $(basename $(draftxml)))
+drafttest     = $(addsuffix .tests, $(basename $(draftxml)))
+drafttxtfiles = $(addprefix tests/out/, $(drafttxt))
+drafttests    = $(addprefix tests/out/, $(drafttest))
+
 pyfiles  = $(wildcard  xml2rfc/*.py) $(wildcard  xml2rfc/writers/*.py)
 
 
@@ -28,9 +40,9 @@ install:
 	python setup.py --quiet install --skip-build
 	rm -rf xml2rfc.egg-info/
 
-test:	install flaketests pytests
+test:	install flaketest pytests
 
-flaketests:
+flaketest:
 	pyflakes xml2rfc
 	[ -d tests/failed/ ] && rm -f tests/failed/*
 
@@ -39,40 +51,49 @@ pytests:
 
 CHECKOUTPUT=	\
 	groff -ms -K$$type -T$$type tmp/$$doc.nroff | ./fix.pl | $$postnrofffix > tmp/$$doc.nroff.txt ;	\
-	for type in .raw.txt .txt .nroff .html .exp.xml .v2v3.xml ; do					\
-	  diff -I '$(datetime_regex)' -I '$(version_regex)' tests/valid/$$doc$$type tmp/$$doc$$type || { echo "Diff failed for $$doc$$type output"; exit 1; } \
+	for type in .raw.txt .txt .nroff .html .exp.xml .v2v3.xml .prepped.xml ; do					\
+	  diff -I '$(datetime_regex)' -I '$(version_regex)' -I '$(date_regex)' tests/valid/$$doc$$type tmp/$$doc$$type || { echo "Diff failed for $$doc$$type output"; exit 1; } \
 	done ; if [ $$type = ascii ]; then echo "Diff nroff output with xml2rfc output:";\
-	diff -I '$(datetime_regex)' -I '$(version_regex)' tmp/$$doc.nroff.txt tmp/$$doc.txt || { echo 'Diff failed for .nroff.txt output'; exit 1; }; fi
+	diff -I '$(datetime_regex)' -I '$(version_regex)' -I '$(date_regex)' tmp/$$doc.nroff.txt tmp/$$doc.txt || { echo 'Diff failed for .nroff.txt output'; exit 1; }; fi
 
 # ----------------------------------------------------------------------
 #
 # Generic rules
 
-%.tests: %.txt.test %.raw.txt.test %.nroff.test %.html.test %.exp.xml.test %.nroff.txt %.v2v3.xml.test
-	@echo "Diffing .nroff.txt against "
-	doc=$(basename $@); diff -I '$(datetime_regex)' -I '$(version_regex)' $$doc.nroff.txt $$doc.txt || { echo 'Diff failed for $$doc.nroff.txt output'; exit 1; }
+%.tests: %.txt.test %.raw.txt.test %.nroff.test %.html.test %.exp.xml.test %.nroff.txt %.v2v3.xml.test %.prepped.xml.test 
+	@echo "Diffing .nroff.txt against regular .txt"
+	doc=$(basename $@); diff -I '$(datetime_regex)' -I '$(version_regex)' -I '$(date_regex)' $$doc.nroff.txt $$doc.txt || { echo 'Diff failed for $$doc.nroff.txt output'; exit 1; }
 	@echo checking v3 validity
 	doc=$(basename $@); xmllint --noout --relaxng xml2rfc/data/v3.rng $$doc.v2v3.xml
+	doc=$(basename $@); xmllint --noout --relaxng xml2rfc/data/v3.rng $$doc.prepped.xml
 
-tests/out/%.txt tests/out/%.raw.txt tests/out/%.nroff tests/out/%.html tests/out/%.txt tests/out/%.exp.xml tests/out/%.v2v3.xml: tests/input/%.xml install
+tests/out/%.txt tests/out/%.raw.txt tests/out/%.nroff tests/out/%.html tests/out/%.txt tests/out/%.exp.xml tests/out/%.v2v3.xml : tests/input/%.xml install
 	@ echo "\nProcessing $<"
-	xml2rfc --cache tests/cache --no-network $< --base tests/out/ --raw --text --nroff --html --exp --v2v3
+	xml2rfc --cache tests/cache --no-network --base tests/out/ --raw --text --nroff --html --exp --v2v3 $<
+
+.PRECIOUS: tests/out/%.txt tests/out/%.raw.txt tests/out/%.nroff tests/out/%.nroff.txt tests/out/%.html tests/out/%.txt tests/out/%.exp.xml tests/out/%.v2v3.xml tests/out/%.prepped.xml %.prepped.xml %.nroff.txt
+
+
+%.prepped.xml: %.v2v3.xml
+	rfc=$(findstring /rfc,$<); xml2rfc --cache tests/cache --no-network --utf8 --out $@ --prep $${rfc:+'--rfc'} $<
 
 %.test: %
 	@echo "Diffing $< against master"
-	diff -I '$(datetime_regex)' -I '$(version_regex)' tests/valid/$(notdir $<) $< || { echo "Diff failed for $< output"; exit 1; }
+	diff -I '$(datetime_regex)' -I '$(version_regex)' -I '$(date_regex)' tests/valid/$(notdir $<) $< || { echo "Diff failed for $< output"; exit 1; }
 
 %.nroff.txt: %.nroff
-	groff -ms -Kascii -Tascii $< | ./fix.pl > $@
+	if [ "$(findstring /rfc,$<)" = "/rfc" ]; then groff -ms -Kascii -Tascii $< | ./fix.pl > $@; else groff -ms -Kascii -Tascii $< | ./fix.pl | sed 1,2d > $@; fi
 
 # ----------------------------------------------------------------------
 
-drafttest: cleantmp install
-	@ xml2rfc --cache tests/cache --no-network tests/input/draft-template.xml --base tmp/ --raw --text --nroff --html --exp --v2v3
+old-drafttest: cleantmp install
+	@ xml2rfc --cache tests/cache --no-network --base tmp/ --raw --text --nroff --html --exp --v2v3 tests/input/draft-template.xml
+	@ xml2rfc --cache tests/cache --no-network --out tmp/draft-template.prepped.xml --prep tmp/draft-template.v2v3.xml 
 	doc=draft-template ; postnrofffix="sed 1,2d" ; type=ascii; $(CHECKOUTPUT)
 
 miektest: cleantmp install
-	@ xml2rfc --cache tests/cache --no-network tests/input/draft-miek-test.xml --base tmp/ --raw --text --nroff --html --exp --v2v3
+	@ xml2rfc --cache tests/cache --no-network --base tmp/ --raw --text --nroff --html --exp --v2v3 tests/input/draft-miek-test.xml
+	@ xml2rfc --cache tests/cache --no-network --out tmp/draft-miek-test.prepped.xml --prep tmp/draft-miek-test.v2v3.xml
 	doc=draft-miek-test ; postnrofffix="sed 1,2d" ; type=ascii; $(CHECKOUTPUT)
 
 cachetest: cleantmp install
@@ -86,21 +107,28 @@ cachetest: cleantmp install
 
 rfctest: cleantmp env/bin/python install $(rfctests)
 
+drafttest: cleantmp env/bin/python install $(drafttests)
+
 # rfctest: cleantmp env/bin/python install $(rfctests)
-# 	@ xml2rfc --cache tests/cache --no-network tests/input/rfc6787.xml --base tmp/ --raw --text --nroff --html --exp --v2v3
+# 	@ xml2rfc --cache tests/cache --no-network --utf8tests/input/rfc6787.xml --base tmp/ --raw --text --nroff --html --exp --v2v3 --prep
 # 	doc=rfc6787 ; postnrofffix="cat" ; type=ascii; $(CHECKOUTPUT)
-# 	@ xml2rfc --cache tests/cache --no-network tests/input/rfc7754.edited.xml --base tmp/ --raw --text --nroff --html --exp --v2v3
+# 	@ xml2rfc --cache tests/cache --no-network --utf8tests/input/rfc7754.edited.xml --base tmp/ --raw --text --nroff --html --exp --v2v3 --prep
 # 	doc=rfc7754.edited ; postnrofffix="cat" ; type=ascii; $(CHECKOUTPUT)
-# 	@ xml2rfc --cache tests/cache --no-network tests/input/rfc7911.xml --base tmp/ --raw --text --nroff --html --exp --v2v3
+# 	@ xml2rfc --cache tests/cache --no-network --utf8tests/input/rfc7911.xml --base tmp/ --raw --text --nroff --html --exp --v2v3 --prep
 # 	doc=rfc7911 ; postnrofffix="cat" ; type=ascii; $(CHECKOUTPUT)
 
 unicodetest: cleantmp  env/bin/python install
-	@ xml2rfc --cache tests/cache --no-network tests/input/unicode.xml --base tmp/ --raw --text --nroff --html --exp --v2v3
+	@ xml2rfc --cache tests/cache --no-network --base tmp/ --raw --text --nroff --html --exp --v2v3 --prep tests/input/unicode.xml 
 	doc=unicode ; postnrofffix="sed 1,2d" ; type=ascii; $(CHECKOUTPUT)
 
 utf8test: cleantmp  env/bin/python install
-	@ xml2rfc --cache tests/cache --no-network --utf8 tests/input/utf8.xml --base tmp/ --raw --text --nroff --html --exp --v2v3
+	@ xml2rfc --cache tests/cache --no-network --utf8 --base tmp/ --raw --text --nroff --html --exp --v2v3 --prep tests/input/utf8.xml
 	doc=utf8 ; postnrofffix="cat" ; type=utf8; $(CHECKOUTPUT)
+
+v3featuretest: cleantmp  env/bin/python install
+	@ xml2rfc --cache tests/cache --no-network --utf8 --base tmp/ --prep tests/input/draft-v3-features.xml
+	diff -I '$(datetime_regex)' -I '$(version_regex)' -I '$(date_regex)' tests/valid/draft-v3-features.prepped.xml tmp/draft-v3-features.prepped.xml || { echo "Diff failed for $$doc$$type output"; exit 1; } 
+
 
 cleantmp:
 	[ -d tmp ] || mkdir -p tmp
@@ -109,14 +137,14 @@ cleantmp:
 	[ -d tests/out ] && rm -f tests/out/* && cp xml2rfc/templates/rfc2629* tests/out/
 
 
-tests: test regressiontests cachetest drafttest miektest
+tests: test regressiontests cachetest drafttest utf8test v3featuretest
 
 noflakestests: install pytests regressiontests
 
-regressiontests: drafttest miektest rfctest
+regressiontests: drafttest rfctest
 
 test2:	test
-	@ xml2rfc --cache tests/cache --no-network tests/input/rfc6635.xml --text --out tmp/rfc6635.txt	&& diff -I '$(datetime_regex)' -I '$(version_regex)' tests/valid/rfc6635.txt tmp/rfc6635.txt 
+	@ xml2rfc --cache tests/cache --no-network --utf8tests/input/rfc6635.xml --text --out tmp/rfc6635.txt	&& diff -I '$(datetime_regex)' -I '$(version_regex)' -I '$(date_regex)' tests/valid/rfc6635.txt tmp/rfc6635.txt 
 
 upload: install
 	rst2html changelog > /dev/null	# verify that the changelog is valid rst
